
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.Level
{
public sealed partial class LevelConfig : Luban.BeanBase
{
    public LevelConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Level = _buf.ReadString();
        Map = _buf.ReadString();
        {int __n0 = _buf.ReadSize(); Waves = new MonsterSpawnWaves[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { MonsterSpawnWaves __e0;__e0 = global::GameConfig.MonsterSpawnWaves.DeserializeMonsterSpawnWaves(_buf); Waves[__index0] = __e0;}}
        Pos = ExternalTypeUtil.NewVector3(global::GameConfig.vector3.Deserializevector3(_buf));
    }

    public static LevelConfig DeserializeLevelConfig(ByteBuf _buf)
    {
        return new Level.LevelConfig(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 关卡
    /// </summary>
    public readonly string Level;
    /// <summary>
    /// 路径
    /// </summary>
    public readonly string Map;
    public readonly MonsterSpawnWaves[] Waves;
    public readonly Godot.Vector3 Pos;
   
    public const int __ID__ = 735472700;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Waves) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "Level:" + Level + ","
        + "Map:" + Map + ","
        + "Waves:" + Luban.StringUtil.CollectionToString(Waves) + ","
        + "pos:" + Pos + ","
        + "}";
    }
}
}

