//------------------------------------------------------------
// Resources Collection Constant
// Auto-generated by ResourcesCollection plugin.
// Do not modify manually.
// Generation time: 2026-07-29 16:07:02
//------------------------------------------------------------

namespace GameConfig.Constant
{
	public static class ResourcesCollectionConstant
	{
		public const string Audios_AudioBundle = "res://TheGame/Audios/AudioBundle.tres";
		public const string Audios_AudioBus = "res://TheGame/Audios/AudioBus.tres";
		public const string DataTables_DataTableBundle = "res://TheGame/DataTables/DataTableBundle.tres";
		public const string GameConfigs_entity_tbentityconfig = "res://TheGame/DataTables/GameConfigs/entity_tbentityconfig.bytes";
		public const string GameConfigs_ui_tbuiformconfig = "res://TheGame/DataTables/GameConfigs/ui_tbuiformconfig.bytes";
		public const string Localizations_ChineseSimplified = "res://TheGame/DataTables/Localizations/ChineseSimplified.txt";
		public const string Localizations_English = "res://TheGame/DataTables/Localizations/English.txt";
		public const string Entitys_AngerEntity = "res://TheGame/Entitys/AngerEntity.tscn";
		public const string Entitys_CatEntity = "res://TheGame/Entitys/CatEntity.tscn";
		public const string Entitys_Drop = "res://TheGame/Entitys/Drop.tscn";
		public const string Entitys_EntityBundle = "res://TheGame/Entitys/EntityBundle.tres";
		public const string Entitys_GanTanEntity = "res://TheGame/Entitys/GanTanEntity.tscn";
		public const string Entitys_LightningBall = "res://TheGame/Entitys/LightningBall.tscn";
		public const string Fonts_simhei = "res://TheGame/MainPack/Fonts/simhei.ttf";
		public const string Resources_EntityGroupRes = "res://TheGame/MainPack/Resources/EntityGroupRes.tres";
		public const string Resources_NodePoolConfigRes = "res://TheGame/MainPack/Resources/NodePoolConfigRes.tres";
		public const string Resources_ScriptGenerateRes = "res://TheGame/MainPack/Resources/ScriptGenerateRes.tres";
		public const string Resources_SoundGroupRes = "res://TheGame/MainPack/Resources/SoundGroupRes.tres";
		public const string Resources_UIGroupRes = "res://TheGame/MainPack/Resources/UIGroupRes.tres";
		public const string Resources_UpdateSettingRes = "res://TheGame/MainPack/Resources/UpdateSettingRes.tres";
		public const string Themes_MainThemes = "res://TheGame/MainPack/Themes/MainThemes.tres";
		public const string UI_LogInForm = "res://TheGame/MainPack/UI/LogInForm.tscn";
		public const string UI_QuestionTips = "res://TheGame/MainPack/UI/QuestionTips.tscn";
		public const string Scenes_ScenesBundle = "res://TheGame/Scenes/ScenesBundle.tres";
		public const string Sprites_SpritesBundle = "res://TheGame/Sprites/SpritesBundle.tres";
		public const string UIs_UIsBundle = "res://TheGame/UIs/UIsBundle.tres";
	}
}
