//------------------------------------------------------------
// Resources Collection Constant
// Auto-generated by GameFrameworkTopMenu plugin.
// Do not modify manually.
// Generation time: 2026-08-11 16:46:01
//------------------------------------------------------------

namespace GameConfig.Constant
{
	public static class ResourcesCollectionConstant
{
		public const string Audios_AudioBundle = "res://TheGame/Audios/AudioBundle.tres";
		public const string Audios_AudioBus = "res://TheGame/Audios/AudioBus.tres";
		public const string Music_Fight = "res://TheGame/Audios/Music/Fight.wav";
		public const string Music_Menu = "res://TheGame/Audios/Music/Menu.wav";
		public const string SFX_AtkUp = "res://TheGame/Audios/SFX/AtkUp.wav";
		public const string SFX_Dead = "res://TheGame/Audios/SFX/Dead.MP3";
		public const string SFX_Heal = "res://TheGame/Audios/SFX/Heal.wav";
		public const string SFX_PaoDan = "res://TheGame/Audios/SFX/PaoDan.mp3";
		public const string SFX_Shoot = "res://TheGame/Audios/SFX/Shoot.mp3";
		public const string DataTables_DataTableBundle = "res://TheGame/DataTables/DataTableBundle.tres";
		public const string GameConfigs_character_tbcharacterconfig = "res://TheGame/DataTables/GameConfigs/character_tbcharacterconfig.bytes";
		public const string GameConfigs_entity_tbentityconfig = "res://TheGame/DataTables/GameConfigs/entity_tbentityconfig.bytes";
		public const string GameConfigs_level_tblevelconfig = "res://TheGame/DataTables/GameConfigs/level_tblevelconfig.bytes";
		public const string GameConfigs_ui_tbuiformconfig = "res://TheGame/DataTables/GameConfigs/ui_tbuiformconfig.bytes";
		public const string Localizations_ChineseSimplified = "res://TheGame/DataTables/Localizations/ChineseSimplified.txt";
		public const string Localizations_English = "res://TheGame/DataTables/Localizations/English.txt";
		public const string Entitys_AngerEntity = "res://TheGame/Entitys/AngerEntity.tscn";
		public const string Entitys_CatEntity = "res://TheGame/Entitys/CatEntity.tscn";
		public const string Entitys_Drop = "res://TheGame/Entitys/Drop.tscn";
		public const string Entitys_EntityBundle = "res://TheGame/Entitys/EntityBundle.tres";
		public const string Entitys_GanTanEntity = "res://TheGame/Entitys/GanTanEntity.tscn";
		public const string Entitys_LightningBall = "res://TheGame/Entitys/LightningBall.tscn";
		public const string Fonts_simhei = "res://TheGame/MainPack/Fonts/simhei.ttf";
		public const string Resources_EntityGroupRes = "res://TheGame/MainPack/Resources/EntityGroupRes.tres";
		public const string Resources_NodePoolConfigRes = "res://TheGame/MainPack/Resources/NodePoolConfigRes.tres";
		public const string Resources_ScriptGenerateRes = "res://TheGame/MainPack/Resources/ScriptGenerateRes.tres";
		public const string Resources_SoundGroupRes = "res://TheGame/MainPack/Resources/SoundGroupRes.tres";
		public const string Resources_UIGroupRes = "res://TheGame/MainPack/Resources/UIGroupRes.tres";
		public const string Resources_UpdateSettingRes = "res://TheGame/MainPack/Resources/UpdateSettingRes.tres";
		public const string Themes_MainThemes = "res://TheGame/MainPack/Themes/MainThemes.tres";
		public const string UI_LoadingForm = "res://TheGame/MainPack/UI/LoadingForm.tscn";
		public const string UI_QuestionTips = "res://TheGame/MainPack/UI/QuestionTips.tscn";
		public const string Scenes_Map = "res://TheGame/Scenes/Map.tscn";
		public const string Scenes_ScenesBundle = "res://TheGame/Scenes/ScenesBundle.tres";
		public const string Characters_enemy_bug = "res://TheGame/Sprites/Characters/enemy_bug.png";
		public const string Wizard_wizard_defeat = "res://TheGame/Sprites/Characters/Wizard/wizard_defeat.png";
		public const string Wizard_wizard_idle = "res://TheGame/Sprites/Characters/Wizard/wizard_idle.png";
		public const string Wizard_wizard_revive = "res://TheGame/Sprites/Characters/Wizard/wizard_revive.png";
		public const string Wizard_wizard_walk_new = "res://TheGame/Sprites/Characters/Wizard/wizard_walk_new.png";
		public const string Sprites_SpritesBundle = "res://TheGame/Sprites/SpritesBundle.tres";
		public const string Stage_back_grass_darkest = "res://TheGame/Sprites/Stage/back_grass_darkest.png";
		public const string UI_ui_button_background = "res://TheGame/Sprites/UI/ui_button_background.png";
		public const string UI_ui_button_blue = "res://TheGame/Sprites/UI/ui_button_blue.png";
		public const string UI_ui_button_brown = "res://TheGame/Sprites/UI/ui_button_brown.png";
		public const string UI_ui_button_gray = "res://TheGame/Sprites/UI/ui_button_gray.png";
		public const string UI_ui_button_green = "res://TheGame/Sprites/UI/ui_button_green.png";
		public const string UI_ui_button_purple = "res://TheGame/Sprites/UI/ui_button_purple.png";
		public const string UI_ui_button_red = "res://TheGame/Sprites/UI/ui_button_red.png";
		public const string UI_ui_button_yellow = "res://TheGame/Sprites/UI/ui_button_yellow.png";
		public const string UI_ui_settings = "res://TheGame/Sprites/UI/ui_settings.png";
		public const string UI_ui_stage_background = "res://TheGame/Sprites/UI/ui_stage_background.png";
		public const string UI_ui_stagel_label = "res://TheGame/Sprites/UI/ui_stagel_label.png";
		public const string VFX_vfx_honey_blob = "res://TheGame/Sprites/VFX/vfx_honey_blob.png";
		public const string VFX_vfx_lightning_ball_red = "res://TheGame/Sprites/VFX/vfx_lightning_ball_red.png";
		public const string VFX_vfx_star = "res://TheGame/Sprites/VFX/vfx_star.png";
		public const string VFX_vfx_wand_projectile = "res://TheGame/Sprites/VFX/vfx_wand_projectile.png";
		public const string UIs_DamagePop = "res://TheGame/UIs/DamagePop.tscn";
		public const string UIs_GameOver = "res://TheGame/UIs/GameOver.tscn";
		public const string UIs_MainForm = "res://TheGame/UIs/MainForm.tscn";
		public const string UIs_MenuForm = "res://TheGame/UIs/MenuForm.tscn";
		public const string UIs_SettingForm = "res://TheGame/UIs/SettingForm.tscn";
		public const string UIs_UIsBundle = "res://TheGame/UIs/UIsBundle.tres";
	}
}
