
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    public UI.TbUIFormConfig TbUIFormConfig {get; }
    public Character.TbCharacterConfig TbCharacterConfig {get; }
    public Entity.TbEntityConfig TbEntityConfig {get; }
    public Level.TbLevelConfig TbLevelConfig {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbUIFormConfig = new UI.TbUIFormConfig(loader("ui_tbuiformconfig"));
        TbCharacterConfig = new Character.TbCharacterConfig(loader("character_tbcharacterconfig"));
        TbEntityConfig = new Entity.TbEntityConfig(loader("entity_tbentityconfig"));
        TbLevelConfig = new Level.TbLevelConfig(loader("level_tblevelconfig"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbUIFormConfig.ResolveRef(this);
        TbCharacterConfig.ResolveRef(this);
        TbEntityConfig.ResolveRef(this);
        TbLevelConfig.ResolveRef(this);
    }
}

}
